version: "3.8"
services:
  db:
    image: postgres
    container_name: mimic-iv-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: geoffray.agard
      POSTGRES_PASSWORD: valeyforge
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: geoffray.agard@free.fr
      PGADMIN_DEFAULT_PASSWORD: valeyforge
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: